/**
 * @file Automatically generated by 'scripts/generate-explicit-api.mjs'.
 */

export type { PatternPlateFrameFormFields } from './ui/PatternPlateFrameForm/schema'
export type { PatternPlateFrameStatus } from './model/status'
export { patternPlateFrameFormSchema } from './ui/PatternPlateFrameForm/schema'
export { patternPlateFrameService } from './api/service'
export { patternPlateFrameStatusOptions } from './model/status'
