/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery,
  type DataTag,
  type DefinedInitialDataOptions,
  type DefinedUseQueryResult,
  type QueryClient,
  type QueryFunction,
  type QueryKey,
  type UndefinedInitialDataOptions,
  type UseQueryOptions,
  type UseQueryResult,
} from '@tanstack/react-query'
import { customMutator } from '../../../mutator'
import type {
  GetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetParams,
  HttpValidationError,
  PatternPlateFrameLookupsListResponse,
} from '../../model'

/**
 * @summary Get Pattern Plate Frame Lookups List
 */
export const getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet = (
  params?: GetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetParams,
  signal?: AbortSignal,
) => {
  return customMutator<PatternPlateFrameLookupsListResponse>({
    url: `/api/v1/pattern-plate-frames/lookups`,
    method: 'GET',
    params,
    signal,
  })
}

export const getGetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetQueryKey = (
  params?: GetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetParams,
) => {
  return [`/api/v1/pattern-plate-frames/lookups`, ...(params ? [params] : [])] as const
}

export const getGetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
  >,
  TError = HttpValidationError,
>(
  params?: GetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
        >,
        TError,
        TData
      >
    >
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>>
  > = ({ signal }) =>
    getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>>
  >
export type GetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetQueryError =
  HttpValidationError

export function useGetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet<
  TData = Awaited<
    ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
  >,
  TError = HttpValidationError,
>(
  params: undefined | GetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
          >,
          TError,
          Awaited<
            ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
          >
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet<
  TData = Awaited<
    ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
  >,
  TError = HttpValidationError,
>(
  params?: GetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
          >,
          TError,
          Awaited<
            ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
          >
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet<
  TData = Awaited<
    ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
  >,
  TError = HttpValidationError,
>(
  params?: GetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
        >,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Pattern Plate Frame Lookups List
 */

export function useGetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet<
  TData = Awaited<
    ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
  >,
  TError = HttpValidationError,
>(
  params?: GetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGet>
        >,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions =
    getGetPatternPlateFrameLookupsListApiV1PatternPlateFramesLookupsGetQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
