/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import { faker } from '@faker-js/faker'
import { delay, http, HttpResponse } from 'msw'
import type { MoldingFlaskLookupsListResponse } from '../../model'

export const getGetMoldingFlaskLookupsListApiV1MoldingFlasksLookupsGetResponseMock = (
  overrideResponse: Partial<MoldingFlaskLookupsListResponse> = {},
): MoldingFlaskLookupsListResponse => ({
  data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.uuid(),
    blueprintNumber: faker.string.alpha({ length: { min: 10, max: 20 } }),
    serialNumber: faker.string.alpha({ length: { min: 10, max: 20 } }),
  })),
  page: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  totalPages: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  totalItems: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  ...overrideResponse,
})

export const getGetMoldingFlaskLookupsListApiV1MoldingFlasksLookupsGetMockHandler = (
  overrideResponse?:
    | MoldingFlaskLookupsListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<MoldingFlaskLookupsListResponse> | MoldingFlaskLookupsListResponse),
) => {
  return http.get('*/api/v1/molding-flasks/lookups', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetMoldingFlaskLookupsListApiV1MoldingFlasksLookupsGetResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}
export const getMoldingFlasksMock = () => [
  getGetMoldingFlaskLookupsListApiV1MoldingFlasksLookupsGetMockHandler(),
]
