/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { CastingProductType } from './castingProductType'

export interface CastingProductLookupResponse {
  id: string
  type: CastingProductType
  name: string
}
