/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */

/**
 * Defines the sand system strategy used for creating a mold. This determines the composition and
layering of the molding sand.

LAYERED: A composite system using two types of sand. A high-quality 'Facing Sand' is applied
to the pattern surface, and the rest of the flask is filled with 'Backing Sand'. Used for high
surface quality requirements.

UNITARY: A single, homogenous sand system (typically 'System Sand') is used for the entire mold.
Common in automated foundries where sand is continuously reclaimed and conditioned.
 */
export type MoldingSandSystem = (typeof MoldingSandSystem)[keyof typeof MoldingSandSystem]

 
export const MoldingSandSystem = {
  layered: 'layered',
  unitary: 'unitary',
} as const
