/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { MoldCavityUpdateMoldCoreOperations } from './moldCavityUpdateMoldCoreOperations'

export interface MoldCavityUpdate {
  castingPatternId?: string
  serialNumber?: string
  moldCoreOperations?: MoldCavityUpdateMoldCoreOperations
  isFunctional?: boolean
}
