/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { MoldCoreTypeLookupResponse } from './moldCoreTypeLookupResponse'

export interface MoldCoreTypeLookupsListResponse {
  data: MoldCoreTypeLookupResponse[]
  page: number
  totalPages: number
  totalItems: number
}
