/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { MoldCavityCreateOperation } from './moldCavityCreateOperation'
import type { MoldCavityDeleteOperation } from './moldCavityDeleteOperation'
import type { MoldCavityUpdateOperation } from './moldCavityUpdateOperation'

export type MoldPassportUpdateMoldCavityOperationsAnyOfItem =
  | MoldCavityCreateOperation
  | MoldCavityUpdateOperation
  | MoldCavityDeleteOperation
