/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { MoldCoreCreate } from './moldCoreCreate'

export interface MoldCavityCreate {
  castingPatternId: string
  serialNumber: string
  moldCores: MoldCoreCreate[]
  isFunctional: boolean
}
