/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { MoldingSandSystem } from './moldingSandSystem'

export interface MoldPassportDataGscUpdate {
  moldingSandSystem?: MoldingSandSystem
  moldingSandNumber?: string
  moldHorizontalDensity?: number
  moldVerticalDensity?: number
}
