/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */

export interface MoldCoreMakingMachineLookupResponse {
  id: string
  brand: string
  model: string
}
