/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { AssetStatus } from './assetStatus'
import type { CastingTechnologyShortResponse } from './castingTechnologyShortResponse'
import type { MoldCavityDetailResponse } from './moldCavityDetailResponse'
import type { MoldingAreaShortResponse } from './moldingAreaShortResponse'
import type { MoldPassportDetailResponseCreatedById } from './moldPassportDetailResponseCreatedById'
import type { MoldPassportDetailResponseDataAsc } from './moldPassportDetailResponseDataAsc'
import type { MoldPassportDetailResponseDataGsc } from './moldPassportDetailResponseDataGsc'
import type { MoldPassportDetailResponseDeletedAt } from './moldPassportDetailResponseDeletedAt'
import type { MoldPassportDetailResponseMoldAssemblyTimestamp } from './moldPassportDetailResponseMoldAssemblyTimestamp'
import type { MoldPassportDetailResponseMoldingFlask } from './moldPassportDetailResponseMoldingFlask'
import type { MoldPassportDetailResponseMoldSequenceInShift } from './moldPassportDetailResponseMoldSequenceInShift'
import type { MoldPassportDetailResponseNotes } from './moldPassportDetailResponseNotes'
import type { MoldPassportDetailResponsePatternPlateFrame } from './moldPassportDetailResponsePatternPlateFrame'
import type { MoldPassportDetailResponsePressingPressure } from './moldPassportDetailResponsePressingPressure'
import type { MoldPassportDetailResponseUpdatedById } from './moldPassportDetailResponseUpdatedById'

export interface MoldPassportDetailResponse {
  deletedAt?: MoldPassportDetailResponseDeletedAt
  createdAt: string
  createdById?: MoldPassportDetailResponseCreatedById
  updatedAt: string
  updatedById?: MoldPassportDetailResponseUpdatedById
  id: string
  isComplete: boolean
  primaryCastingProductName: string
  referenceCode: string
  moldingArea: MoldingAreaShortResponse
  castingTechnology: CastingTechnologyShortResponse
  patternPlateFrame?: MoldPassportDetailResponsePatternPlateFrame
  moldingFlask?: MoldPassportDetailResponseMoldingFlask
  dataGsc?: MoldPassportDetailResponseDataGsc
  dataAsc?: MoldPassportDetailResponseDataAsc
  moldCavities: MoldCavityDetailResponse[]
  pressingPressure?: MoldPassportDetailResponsePressingPressure
  moldSequenceInShift?: MoldPassportDetailResponseMoldSequenceInShift
  moldAssemblyTimestamp?: MoldPassportDetailResponseMoldAssemblyTimestamp
  status: AssetStatus
  notes?: MoldPassportDetailResponseNotes
  readonly isDeleted: boolean
}
