/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { MoldCavityCreate } from './moldCavityCreate'
import type { MoldPassportCreateAssemblyTimestamp } from './moldPassportCreateAssemblyTimestamp'
import type { MoldPassportCreateDataAsc } from './moldPassportCreateDataAsc'
import type { MoldPassportCreateDataGsc } from './moldPassportCreateDataGsc'
import type { MoldPassportCreateIsDefective } from './moldPassportCreateIsDefective'
import type { MoldPassportCreateMarkingYear } from './moldPassportCreateMarkingYear'
import type { MoldPassportCreateMoldingFlaskId } from './moldPassportCreateMoldingFlaskId'
import type { MoldPassportCreateNotes } from './moldPassportCreateNotes'
import type { MoldPassportCreatePatternPlateFrameId } from './moldPassportCreatePatternPlateFrameId'
import type { MoldPassportCreatePressingPressure } from './moldPassportCreatePressingPressure'
import type { MoldPassportCreateSequenceInShift } from './moldPassportCreateSequenceInShift'

export interface MoldPassportCreate {
  moldingAreaId: number
  castingTechnologyId: number
  patternPlateFrameId?: MoldPassportCreatePatternPlateFrameId
  moldingFlaskId?: MoldPassportCreateMoldingFlaskId
  dataGsc?: MoldPassportCreateDataGsc
  dataAsc?: MoldPassportCreateDataAsc
  moldCavities: MoldCavityCreate[]
  pressingPressure?: MoldPassportCreatePressingPressure
  sequenceInShift?: MoldPassportCreateSequenceInShift
  markingYear?: MoldPassportCreateMarkingYear
  assemblyTimestamp: MoldPassportCreateAssemblyTimestamp
  isDefective?: MoldPassportCreateIsDefective
  notes?: MoldPassportCreateNotes
}
