/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { MoldPassportDataGscCreate } from './moldPassportDataGscCreate'

export type MoldPassportCreateDataGsc = MoldPassportDataGscCreate | null
