/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { MoldCoreCreateOperation } from './moldCoreCreateOperation'
import type { MoldCoreDeleteOperation } from './moldCoreDeleteOperation'
import type { MoldCoreUpdateOperation } from './moldCoreUpdateOperation'

export type MoldCavityUpdateMoldCoreOperationsAnyOfItem =
  | MoldCoreCreateOperation
  | MoldCoreUpdateOperation
  | MoldCoreDeleteOperation
