/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { CastingPatternLookupResponse } from './castingPatternLookupResponse'
import type { MoldCoreDetailResponse } from './moldCoreDetailResponse'

export interface MoldCavityDetailResponse {
  createdAt: string
  updatedAt: string
  id: string
  castingPattern: CastingPatternLookupResponse
  serialNumber: string
  moldCores: MoldCoreDetailResponse[]
  isFunctional: boolean
}
