/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { AssetStatus } from './assetStatus'
import type { MoldingAreaShortResponse } from './moldingAreaShortResponse'

export interface PatternPlateFrameShortResponse {
  id: string
  serialNumber: string
  blueprintNumber: string
  moldingAreas: MoldingAreaShortResponse[]
  status: AssetStatus
}
