/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */

export type ResinType = (typeof ResinType)[keyof typeof ResinType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResinType = {
  mold_core: 'mold_core',
  universal: 'universal',
} as const
