/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import type { ResinType } from './resinType'

export interface ResinShortResponse {
  id: string
  type: ResinType
  brand: string
  name: string
  serialNumber: string
}
