services:
  frontend:
    build:
      context: .
      target: production
    image: test-react-soil-lab:${IMAGE_TAG:-latest}
    ports:
      - '81:80'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 5s
      retries: 3
