/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import { faker } from '@faker-js/faker'
import { delay, http, HttpResponse } from 'msw'
import { CastingProductType, type CastingProductLookupsListResponse } from '../../model'

export const getGetCastingProductLookupsListApiV1CastingProductsLookupsGetResponseMock = (
  overrideResponse: Partial<CastingProductLookupsListResponse> = {},
): CastingProductLookupsListResponse => ({
  data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.uuid(),
    type: faker.helpers.arrayElement(Object.values(CastingProductType)),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    blueprintNumber: faker.string.alpha({ length: { min: 10, max: 20 } }),
    isCastingManualOnly: faker.datatype.boolean(),
  })),
  page: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  totalPages: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  totalItems: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  ...overrideResponse,
})

export const getGetCastingProductLookupsListApiV1CastingProductsLookupsGetMockHandler = (
  overrideResponse?:
    | CastingProductLookupsListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CastingProductLookupsListResponse> | CastingProductLookupsListResponse),
) => {
  return http.get('*/api/v1/casting-products/lookups', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetCastingProductLookupsListApiV1CastingProductsLookupsGetResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}
export const getCastingProductsMock = () => [
  getGetCastingProductLookupsListApiV1CastingProductsLookupsGetMockHandler(),
]
