/**
 * @file Automatically generated by 'scripts/generate-explicit-api.mjs'.
 */

export type { MoldPassportCreateBaseFormProps } from './ui/MoldPassportForm/MoldPassportCreateBaseForm';
export type { MoldPassportCreateFormFields } from './ui/MoldPassportForm/schema';
export type { MoldPassportDataGsc, MoldPassportDataAsc } from './ui/MoldPassportForm/configs/dynamic-fields';
export type { MoldPassportStatus } from './model/status';
export { CastingTechnologyDataGscDynamicForm, CastingTechnologyPassportDataAscDynamicForm } from './ui/MoldPassportForm/components/CastingTechnologySpecificFields';
export { MoldPassportCreateBaseForm } from './ui/MoldPassportForm/MoldPassportCreateBaseForm';
export { MoldPassportCreateForm } from './ui/MoldPassportForm/MoldPassportCreateForm';
export { MoldPassportCreateFormKit } from './ui/MoldPassportForm/FormKit';
export { MoldingAreaDataDynamicForm } from './ui/MoldPassportForm/components/MoldingAreaIdSpecificFields';
export { dataGscFormSchema, dataAscFormSchema, moldPassportDynamicSections } from './ui/MoldPassportForm/configs/dynamic-fields';
export { moldPassportCreateFormSchema, moldPassportCreateFormDefaultValues } from './ui/MoldPassportForm/schema';
export { moldPassportStatusOptions } from './model/status';
export { useMoldPassportFormOptions } from './hooks/useMoldPassportFormOptions';
export { useMoldPassportService } from './api/service';
