/**
 * @file Automatically generated by 'scripts/generate-explicit-api.mjs'.
 */

export type {
  MoldPassportDataGsc,
  MoldPassportDataAsc,
} from './ui/MoldPassportForm/configs/dynamic-fields'
export type { MoldPassportFormFields } from './ui/MoldPassportForm/schema'
export type { MoldPassportStatus } from './model/status'
export {
  CastingTechnologyDataGscDynamicForm,
  CastingTechnologyPassportDataAscDynamicForm,
} from './ui/MoldPassportForm/components/CastingTechnologySpecificFields'
export { MoldPassportForm } from './ui/MoldPassportForm/MoldPassportForm'
export { MoldingAreaDataDynamicForm } from './ui/MoldPassportForm/components/MoldingAreaIdSpecificFields'
export {
  dataGscFormSchema,
  dataAscFormSchema,
  moldPassportDynamicSections,
} from './ui/MoldPassportForm/configs/dynamic-fields'
export { moldPassportFormSchema, moldPassportFormDefaultValues } from './ui/MoldPassportForm/schema'
export { moldPassportRoutes } from '../../../pages/soil-lab/mold-passport/routes'
export { moldPassportStatusOptions } from './model/status'
export { useMoldPassportService } from './api/service'
