/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import { faker } from '@faker-js/faker'
import { delay, http, HttpResponse } from 'msw'
import type { ResinLookupsListResponse } from '../../model'

export const getGetResinLookupsListApiV1ResinsLookupsGetResponseMock = (
  overrideResponse: Partial<ResinLookupsListResponse> = {},
): ResinLookupsListResponse => ({
  data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.uuid(),
    brand: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    serialNumber: faker.string.alpha({ length: { min: 10, max: 20 } }),
  })),
  page: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  totalPages: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  totalItems: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  ...overrideResponse,
})

export const getGetResinLookupsListApiV1ResinsLookupsGetMockHandler = (
  overrideResponse?:
    | ResinLookupsListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ResinLookupsListResponse> | ResinLookupsListResponse),
) => {
  return http.get('*/api/v1/resins/lookups', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetResinLookupsListApiV1ResinsLookupsGetResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}
export const getResinsMock = () => [getGetResinLookupsListApiV1ResinsLookupsGetMockHandler()]
