/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import { faker } from '@faker-js/faker'
import { delay, http, HttpResponse } from 'msw'
import type { CastingTechnologyLookupsListResponse } from '../../model'

export const getGetCastingTechnologyLookupsListApiV1CastingTechnologiesLookupsGetResponseMock = (
  overrideResponse: Partial<CastingTechnologyLookupsListResponse> = {},
): CastingTechnologyLookupsListResponse => ({
  data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    abbreviation: faker.string.alpha({ length: { min: 10, max: 20 } }),
  })),
  page: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  totalPages: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  totalItems: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  ...overrideResponse,
})

export const getGetCastingTechnologyLookupsListApiV1CastingTechnologiesLookupsGetMockHandler = (
  overrideResponse?:
    | CastingTechnologyLookupsListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CastingTechnologyLookupsListResponse> | CastingTechnologyLookupsListResponse),
) => {
  return http.get('*/api/v1/casting-technologies/lookups', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetCastingTechnologyLookupsListApiV1CastingTechnologiesLookupsGetResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}
export const getCastingTechnologiesMock = () => [
  getGetCastingTechnologyLookupsListApiV1CastingTechnologiesLookupsGetMockHandler(),
]
