/**
 * @file Automatically generated by 'scripts/generate-explicit-api.mjs'.
 */

export type { ResinComponent } from './model/component'
export type { ResinFormFields } from './ui/MoldingFlaskForm/schema'
export type { ResinType } from './model/type'
export { resinComponentOptions } from './model/component'
export { resinFormSchema } from './ui/MoldingFlaskForm/schema'
export { resinService } from './api/service'
export { resinTypeOptions } from './model/type'
