/**
 * @file Automatically generated by 'scripts/generate-explicit-api.mjs'.
 */

export type { ResinComponent } from './model/component';
export type { ResinFormFields } from './ui/MoldingFlaskForm/schema';
export type { ResinFormOptions, ResinFormInitialData } from './ui/MoldingFlaskForm/MoldingFlaskForm';
export type { ResinType } from './model/type';
export { default as ResinForm } from './ui/MoldingFlaskForm/MoldingFlaskForm';
export { resinComponentOptions } from './model/component';
export { resinFormSchema } from './ui/MoldingFlaskForm/schema';
export { resinFrameRoutes } from './routes';
export { resinTypeOptions } from './model/type';
