/**
 * @file Automatically generated by 'scripts/generate-explicit-api.mjs'.
 */

export type { MoldPassportDynamicFieldOptions, MoldPassportDataGsc, MoldPassportDataAsc } from './ui/MoldPassportForm/configs/dynamic-fields';
export type { MoldPassportFormFields } from './ui/MoldPassportForm/schema';
export type { MoldPassportFormInitialData } from './ui/MoldPassportForm/MoldPassportForm';
export type { MoldPassportStatus } from './model/status';
export { CastingTechnologyDataGscDynamicForm, CastingTechnologyPassportDataAscDynamicForm } from './ui/MoldPassportForm/components/CastingTechnologySpecificFields';
export { MoldingAreaDataDynamicForm } from './ui/MoldPassportForm/components/MoldingAreaIdSpecificFields';
export { dataGscFormSchema, dataAscFormSchema, moldPassportDynamicFieldConfig } from './ui/MoldPassportForm/configs/dynamic-fields';
export { default as MoldPassportForm } from './ui/MoldPassportForm/MoldPassportForm';
export { moldPassportFormSchema, moldPassportFormDefaultValues } from './ui/MoldPassportForm/schema';
export { moldPassportRoutes } from './routes';
export { moldPassportService } from './api/service';
export { moldPassportStatusOptions } from './model/status';
