/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery,
  type DataTag,
  type DefinedInitialDataOptions,
  type DefinedUseQueryResult,
  type QueryClient,
  type QueryFunction,
  type QueryKey,
  type UndefinedInitialDataOptions,
  type UseQueryOptions,
  type UseQueryResult,
} from '@tanstack/react-query'
import { customMutator } from '../../../mutator'
import type {
  GetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetParams,
  HttpValidationError,
  MoldCoreTypeLookupsListResponse,
} from '../../model'

/**
 * @summary Get Mold Core Type Lookups List
 */
export const getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet = (
  params?: GetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetParams,
  signal?: AbortSignal,
) => {
  return customMutator<MoldCoreTypeLookupsListResponse>({
    url: `/api/v1/mold-core-types/lookups`,
    method: 'GET',
    params,
    signal,
  })
}

export const getGetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetQueryKey = (
  params?: GetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetParams,
) => {
  return [`/api/v1/mold-core-types/lookups`, ...(params ? [params] : [])] as const
}

export const getGetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
  TError = HttpValidationError,
>(
  params?: GetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
        TError,
        TData
      >
    >
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>
  > = ({ signal }) => getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>
>
export type GetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetQueryError = HttpValidationError

export function useGetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet<
  TData = Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
  TError = HttpValidationError,
>(
  params: undefined | GetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
          TError,
          Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet<
  TData = Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
  TError = HttpValidationError,
>(
  params?: GetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
          TError,
          Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet<
  TData = Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
  TError = HttpValidationError,
>(
  params?: GetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Mold Core Type Lookups List
 */

export function useGetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet<
  TData = Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
  TError = HttpValidationError,
>(
  params?: GetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGet>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMoldCoreTypeLookupsListApiV1MoldCoreTypesLookupsGetQueryOptions(
    params,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
