/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */

export type GetParameterLookupsListApiV1ParametersLookupsGetParams = {
  /**
   * @minimum 1
   */
  page?: number
  /**
   * @minimum 1
   * @maximum 20
   */
  per_page?: number
}
