/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { MaterialSourceListItemResponse } from './materialSourceListItemResponse'

export interface MaterialSourcePaginatedListResponse {
  data: MaterialSourceListItemResponse[]
  page: number
  totalPages: number
  totalItems: number
}
