/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */

export interface MaterialTypeShortResponse {
  id: string
  code: string
  name: string
}
