/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { MaterialTypeListItemResponseArchivedAt } from './materialTypeListItemResponseArchivedAt'

export interface MaterialTypeListItemResponse {
  archivedAt?: MaterialTypeListItemResponseArchivedAt
  createdAt: string
  updatedAt: string
  id: string
  code: string
  name: string
  readonly isArchived: boolean
}
