/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { MeasurementListItemResponse } from './measurementListItemResponse'

export interface MeasurementListResponse {
  data: MeasurementListItemResponse[]
  page: number
  totalPages: number
  totalItems: number
}
