/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { MeasurementsReportGenerationRequestDateFrom } from './measurementsReportGenerationRequestDateFrom'
import type { MeasurementsReportGenerationRequestDateTo } from './measurementsReportGenerationRequestDateTo'

export interface MeasurementsReportGenerationRequest {
  dateFrom?: MeasurementsReportGenerationRequestDateFrom
  dateTo?: MeasurementsReportGenerationRequestDateTo
}
