/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */

export interface MeasurementLookupResponse {
  id: string
  moldingSandNumber: string
  moldingSandStrengthKgfCm2: number
  moldingSandGasPermeability: number
  moldingSandMoisturePercent: number
}
