/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { ParameterListItemResponseArchivedAt } from './parameterListItemResponseArchivedAt'

export interface ParameterListItemResponse {
  archivedAt?: ParameterListItemResponseArchivedAt
  createdAt: string
  updatedAt: string
  id: string
  code: string
  name: string
  units: string
  readonly isArchived: boolean
}
