/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { MaterialShortResponse } from './materialShortResponse'
import type { MaterialSourceShortResponse } from './materialSourceShortResponse'
import type { SampleListItemResponseCreatedById } from './sampleListItemResponseCreatedById'
import type { SampleListItemResponseDeletedAt } from './sampleListItemResponseDeletedAt'
import type { SampleListItemResponseUpdatedById } from './sampleListItemResponseUpdatedById'
import type { TestResultShortResponse } from './testResultShortResponse'

export interface SampleListItemResponse {
  deletedAt?: SampleListItemResponseDeletedAt
  createdAt: string
  createdById?: SampleListItemResponseCreatedById
  updatedAt: string
  updatedById?: SampleListItemResponseUpdatedById
  id: string
  material: MaterialShortResponse
  materialSource: MaterialSourceShortResponse
  receivedAt: string
  temperature: number
  testResults: TestResultShortResponse[]
  readonly isDeleted: boolean
}
