/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { MaterialShortResponse } from './materialShortResponse'
import type { MaterialSourceShortResponse } from './materialSourceShortResponse'
import type { SampleDetailResponseCreatedById } from './sampleDetailResponseCreatedById'
import type { SampleDetailResponseDeletedAt } from './sampleDetailResponseDeletedAt'
import type { SampleDetailResponseNote } from './sampleDetailResponseNote'
import type { SampleDetailResponseUpdatedById } from './sampleDetailResponseUpdatedById'
import type { TestResultShortResponse } from './testResultShortResponse'

export interface SampleDetailResponse {
  deletedAt?: SampleDetailResponseDeletedAt
  createdAt: string
  createdById?: SampleDetailResponseCreatedById
  updatedAt: string
  updatedById?: SampleDetailResponseUpdatedById
  id: string
  material: MaterialShortResponse
  materialSource: MaterialSourceShortResponse
  temperature: number
  receivedAt: string
  testResults: TestResultShortResponse[]
  note: SampleDetailResponseNote
  readonly isDeleted: boolean
}
