/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { SampleListItemResponseCreatedById } from './sampleListItemResponseCreatedById'
import type { SampleListItemResponseDeletedAt } from './sampleListItemResponseDeletedAt'
import type { SampleListItemResponseUpdatedById } from './sampleListItemResponseUpdatedById'
import type { TestShortResponse } from './testShortResponse'

export interface SampleListItemResponse {
  deletedAt?: SampleListItemResponseDeletedAt
  createdAt: string
  createdById?: SampleListItemResponseCreatedById
  updatedAt: string
  updatedById?: SampleListItemResponseUpdatedById
  id: string
  moldingSandRecipe: string
  receivedAt: string
  tests: TestShortResponse[]
  readonly isDeleted: boolean
}
