/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */

export type TestType = (typeof TestType)[keyof typeof TestType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TestType = {
  strength: 'strength',
  gas_permeability: 'gas_permeability',
  moisture_percent: 'moisture_percent',
  // new
  tensile_strength: 'tensile_strength',
  tensile_strength_0h: 'tensile_strength_0h',
  tensile_strength_1h: 'tensile_strength_1h',
  tensile_strength_3h: 'tensile_strength_3h',
  tensile_strength_24h: 'tensile_strength_24h',
  gas_evolution: 'gas_evolution',
} as const
