/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { ParameterShortResponse } from './parameterShortResponse'
import type { SampleShortResponse } from './sampleShortResponse'
import type { TestResultListItemResponseCreatedById } from './testResultListItemResponseCreatedById'
import type { TestResultListItemResponseDeletedAt } from './testResultListItemResponseDeletedAt'
import type { TestResultListItemResponseMeanValue } from './testResultListItemResponseMeanValue'
import type { TestResultListItemResponseUpdatedById } from './testResultListItemResponseUpdatedById'
import type { TestResultListItemResponseVariationPercentage } from './testResultListItemResponseVariationPercentage'

export interface TestResultListItemResponse {
  deletedAt?: TestResultListItemResponseDeletedAt
  createdAt: string
  createdById?: TestResultListItemResponseCreatedById
  updatedAt: string
  updatedById?: TestResultListItemResponseUpdatedById
  id: string
  sample: SampleShortResponse
  parameter: ParameterShortResponse
  meanValue: TestResultListItemResponseMeanValue
  variationPercentage: TestResultListItemResponseVariationPercentage
  isCompliant: boolean
  readonly isDeleted: boolean
}
