/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { TestStatus } from './testStatus'
import type { TestType } from './testType'

export interface TestShortResponse {
  id: string
  type: TestType
  meanMeasurement: number
  status: TestStatus
}
