/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { ParameterShortResponse } from './parameterShortResponse'
import type { TestResultShortResponseMeanValue } from './testResultShortResponseMeanValue'
import type { TestResultShortResponseVariationPercentage } from './testResultShortResponseVariationPercentage'

export interface TestResultShortResponse {
  id: string
  parameter: ParameterShortResponse
  meanValue: TestResultShortResponseMeanValue
  variationPercentage: TestResultShortResponseVariationPercentage
  isCompliant: boolean
}
