/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { PermissionDetailResponse } from './permissionDetailResponse'
import type { RoleDetailResponse } from './roleDetailResponse'
import type { UserDetailResponseCreatedById } from './userDetailResponseCreatedById'
import type { UserDetailResponseDeletedAt } from './userDetailResponseDeletedAt'
import type { UserDetailResponseLastLoginAt } from './userDetailResponseLastLoginAt'
import type { UserDetailResponseUpdatedById } from './userDetailResponseUpdatedById'

export interface UserDetailResponse {
  deletedAt?: UserDetailResponseDeletedAt
  createdAt: string
  createdById?: UserDetailResponseCreatedById
  updatedAt: string
  updatedById?: UserDetailResponseUpdatedById
  id: string
  firstName: string
  lastName: string
  email: string
  isActive: boolean
  isSuperuser: boolean
  lastLoginAt?: UserDetailResponseLastLoginAt
  roles: RoleDetailResponse[]
  permissions: PermissionDetailResponse[]
  readonly isDeleted: boolean
}
