/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { PermissionDetailResponse } from './permissionDetailResponse'
import type { RoleDetailResponse } from './roleDetailResponse'
import type { UserListItemResponseDeletedAt } from './userListItemResponseDeletedAt'
import type { UserListItemResponseLastLoginAt } from './userListItemResponseLastLoginAt'

export interface UserListItemResponse {
  deletedAt?: UserListItemResponseDeletedAt
  id: string
  firstName: string
  lastName: string
  email: string
  isActive: boolean
  isSuperuser: boolean
  lastLoginAt?: UserListItemResponseLastLoginAt
  roles: RoleDetailResponse[]
  permissions: PermissionDetailResponse[]
  readonly isDeleted: boolean
}
