/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { PermissionCreateDescription } from './permissionCreateDescription'

export interface PermissionCreate {
  /**
   * @minLength 5
   * @maxLength 255
   */
  code: string
  /**
   * @minLength 2
   * @maxLength 120
   */
  name: string
  description?: PermissionCreateDescription
}
