/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { PermissionDetailResponseArchivedAt } from './permissionDetailResponseArchivedAt'
import type { PermissionDetailResponseDescription } from './permissionDetailResponseDescription'

export interface PermissionDetailResponse {
  archivedAt?: PermissionDetailResponseArchivedAt
  createdAt: string
  updatedAt: string
  id: string
  code: string
  name: string
  description?: PermissionDetailResponseDescription
  readonly isArchived: boolean
}
