/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { SampleListItemResponse } from './sampleListItemResponse'

export interface SampleListResponse {
  data: SampleListItemResponse[]
  page: number
  totalPages: number
  totalItems: number
}
