/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { SampleShortResponse } from './sampleShortResponse'
import type { TestDetailResponseCreatedById } from './testDetailResponseCreatedById'
import type { TestDetailResponseDeletedAt } from './testDetailResponseDeletedAt'
import type { TestDetailResponseMeasurement3 } from './testDetailResponseMeasurement3'
import type { TestDetailResponseUpdatedById } from './testDetailResponseUpdatedById'
import type { TestStatus } from './testStatus'
import type { TestType } from './testType'

export interface TestDetailResponse {
  deletedAt?: TestDetailResponseDeletedAt
  createdAt: string
  createdById?: TestDetailResponseCreatedById
  updatedAt: string
  updatedById?: TestDetailResponseUpdatedById
  id: string
  type: TestType
  sample: SampleShortResponse
  measurement1: number
  measurement2: number
  measurement3: TestDetailResponseMeasurement3
  selectedMeasurement1: number
  selectedMeasurement2: number
  differencePercent: number
  meanMeasurement: number
  lowerLimit: number
  upperLimit: number
  status: TestStatus
  readonly isDeleted: boolean
}
