/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * soil_laboratory
 * OpenAPI spec version: 0.1.0
 */
import type { TestListItemResponseCreatedById } from './testListItemResponseCreatedById'
import type { TestListItemResponseDeletedAt } from './testListItemResponseDeletedAt'
import type { TestListItemResponseUpdatedById } from './testListItemResponseUpdatedById'
import type { TestStatus } from './testStatus'
import type { TestType } from './testType'

export interface TestListItemResponse {
  deletedAt?: TestListItemResponseDeletedAt
  createdAt: string
  createdById?: TestListItemResponseCreatedById
  updatedAt: string
  updatedById?: TestListItemResponseUpdatedById
  id: string
  type: TestType
  meanMeasurement: number
  status: TestStatus
  readonly isDeleted: boolean
}
