import { execSync } from 'child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import path from 'path'

// --- Начало: Эта часть не изменилась ---
const config = JSON.parse(readFileSync('./api-services.config.json', 'utf-8'))
const serviceName = process.argv[2]

if (!serviceName) {
  console.error('❌ Ошибка: Не указано имя сервиса.')
  console.log('✅ Пример: npm run api main')
  process.exit(1)
}

const service = config[serviceName]

if (!service) {
  console.error(`❌ Ошибка: Сервис с именем "${serviceName}" не найден в api-services.config.json.`)
  process.exit(1)
}

const { url, path: servicePath } = service

// Убедимся, что директория сервиса существует
if (!existsSync(servicePath)) {
  mkdirSync(servicePath, { recursive: true })
}

const openapiJsonPath = path.join(servicePath, 'openapi.json')
const schemaTsPath = path.join(servicePath, 'schema.ts')
const typesTsPath = path.join(servicePath, 'types.ts') // Путь к новому файлу
const casingFilePath = 'casing.yaml'
// --- Конец: Эта часть не изменилась ---

try {
  console.log(`🚀 [${serviceName}] Шаг 1/3: Получение и форматирование схемы...`)
  execSync(`npx openapi-format ${url} -o ${openapiJsonPath} --casingFile ${casingFilePath}`, {
    stdio: 'inherit',
  })

  console.log(`🚀 [${serviceName}] Шаг 2/3: Генерация основного файла типов schema.ts...`)
  execSync(`npx openapi-typescript ${openapiJsonPath} -o ${schemaTsPath}`, { stdio: 'inherit' })

  console.log(`🚀 [${serviceName}] Шаг 3/3: Генерация файла с псевдонимами types.ts...`)

  // Читаем только что созданный openapi.json
  const apiSpec = JSON.parse(readFileSync(openapiJsonPath, 'utf-8'))
  const schemas = apiSpec.components?.schemas

  if (!schemas) {
    console.warn(
      `⚠️ [${serviceName}] В схеме не найден раздел components.schemas. Файл types.ts не будет создан.`,
    )
  } else {
    const schemaNames = Object.keys(schemas)

    // Формируем содержимое файла types.ts
    const header = `/**
 * This file was auto-generated by scripts/generateApi.mjs.
 * Do not make direct changes to the file.
 */\n\nimport type { components } from './schema';\n\n`
    const typeAliases = schemaNames
      .map((name) => `export type ${name} = components['schemas']['${name}'];`)
      .join('\n')

    writeFileSync(typesTsPath, header + typeAliases, 'utf-8')
    console.log(
      `✅ [${serviceName}] Файл types.ts успешно создан с ${schemaNames.length} псевдонимами.`,
    )
  }

  console.log(`\n🎉 [${serviceName}] Готово! Все типы успешно сгенерированы.`)
} catch (error) {
  console.error(`❌ [${serviceName}] Произошла ошибка во время генерации API:`, error.message)
  process.exit(1)
}
