// scripts/generateDtoSchema.mjs
import fs from 'fs/promises'
import path from 'path'
import process from 'process'
import { pathToFileURL } from 'url'

// --- КОНФИГУРАЦИЯ ---
const DEFAULT_SCHEMA_PATH = 'src/shared/api/main/schema.ts' // Приоритетный путь по умолчанию
const DEFAULT_SEARCH_DIR = 'src/shared/api' // Папка для автопоиска, если схема по умолчанию не найдена
const TARGET_FILENAME = 'dto.ts'

// --- ХЕЛПЕРЫ ---
const toPascalCase = (str) => str.charAt(0).toUpperCase() + str.slice(1)

async function findSchemaFiles(dir) {
  let results = []
  try {
    const dirents = await fs.readdir(dir, { withFileTypes: true })
    for (const dirent of dirents) {
      const resolvedPath = path.resolve(dir, dirent.name)
      if (dirent.isDirectory()) {
        results = results.concat(await findSchemaFiles(resolvedPath))
      } else if (dirent.name === 'schema.ts') {
        results.push(resolvedPath)
      }
    }
  } catch (error) {
    // Игнорируем ошибку, если директория не найдена
    if (error.code !== 'ENOENT') throw error
  }
  return results
}

// --- ОСНОВНАЯ ЛОГИКА ---
const main = async () => {
  try {
    const [, , entityName, targetPathInput, schemaPathInput] = process.argv

    if (!entityName || !targetPathInput) {
      console.error(
        '❌ Использование: node scripts/generateDtoSchema.mjs <EntityName> <TargetDirectory> [SchemaPath]',
      )
      process.exit(1)
    }

    const entity = toPascalCase(entityName)
    let schemaPath = ''

    if (schemaPathInput) {
      // 1. Приоритет: путь, указанный вручную.
      schemaPath = path.resolve(schemaPathInput)
      console.log(`ℹ️  Использую явно указанный путь к схеме: ${schemaPath}`)
    } else {
      // 2. Путь не указан, пробуем путь по умолчанию.
      const defaultPath = path.resolve(DEFAULT_SCHEMA_PATH)
      try {
        await fs.access(defaultPath)
        schemaPath = defaultPath
        console.log(`ℹ️  Использую схему по умолчанию: ${schemaPath}`)
      } catch {
        // 3. Схема по умолчанию не найдена, начинаем автоматический поиск.
        const searchDir = path.resolve(DEFAULT_SEARCH_DIR)
        console.warn(
          `🟡 Схема по умолчанию не найдена. Начинаю поиск 'schema.ts' в ${searchDir}...`,
        )
        const foundFiles = await findSchemaFiles(searchDir)

        if (foundFiles.length === 0) {
          throw new Error(
            `Не найдено ни одного файла 'schema.ts' в ${searchDir}. Укажи путь к схеме вручную.`,
          )
        }
        if (foundFiles.length > 1) {
          throw new Error(
            `Найдено несколько файлов 'schema.ts'. Уточни, какой из них использовать, передав путь как третий аргумент:\n- ${foundFiles.join('\n- ')}`,
          )
        }

        schemaPath = foundFiles[0]
        console.log(`✅ Найдена одна схема: ${schemaPath}`)
      }
    }

    // Проверяем доступность финального файла схемы
    try {
      await fs.access(schemaPath)
    } catch (error) {
      throw new Error(`Файл схемы не найден по пути: ${schemaPath}`)
    }

    // Динамически импортируем файл схемы
    const schemaModule = await import(pathToFileURL(schemaPath).href)
    if (!schemaModule.components?.schemas) {
      throw new Error(
        'Ошибка в файле схемы: не найден экспорт `components` или `components.schemas`.',
      )
    }

    const allSchemaNames = Object.keys(schemaModule.components.schemas)
    const entityTypeNames = allSchemaNames.filter((name) => name.startsWith(entity))

    if (entityTypeNames.length === 0) {
      console.warn(`⚠️  Не найдено схем, начинающихся с "${entity}". Файл не будет создан.`)
      return
    }

    console.log(`✅ Найдено ${entityTypeNames.length} DTO для сущности "${entity}".`)

    let targetDir = path.resolve(targetPathInput)
    try {
      const targetStats = await fs.stat(targetDir)
      if (targetStats.isFile()) targetDir = path.dirname(targetDir)
    } catch {}

    await fs.mkdir(targetDir, { recursive: true })

    const relativePathToSchema = path
      .relative(targetDir, schemaPath)
      .replace(/\\/g, '/')
      .replace(/\.ts$/, '')
    const header = `/**
 * @file Data Transfer Objects for ${entity}.
 * @note This file was auto-generated by a script. Do not edit it manually.
 */\n
import type { components } from '${relativePathToSchema}';\n`

    const typeAliases = entityTypeNames
      .sort()
      .map((name) => `export type ${name} = components['schemas']['${name}'];`)
      .join('\n')
    const fileContent = `${header}\n${typeAliases}\n`
    const targetFilePath = path.join(targetDir, TARGET_FILENAME)

    await fs.writeFile(targetFilePath, fileContent, 'utf-8')
    console.log(`✅ Файл DTO успешно создан: ${targetFilePath}`)
  } catch (err) {
    console.error(`❌ Ошибка при генерации DTO: ${err.message}`)
    process.exit(1)
  }
}

main()
