/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery,
  type DataTag,
  type DefinedInitialDataOptions,
  type DefinedUseQueryResult,
  type QueryClient,
  type QueryFunction,
  type QueryKey,
  type UndefinedInitialDataOptions,
  type UseQueryOptions,
  type UseQueryResult,
} from '@tanstack/react-query'
import { customMutator } from '../../../mutator'
import type {
  CastingPatternLookupsListResponse,
  GetCastingPatternLookupsListApiV1CastingPatternsLookupsGetParams,
  HttpValidationError,
} from '../../model'

/**
 * @summary Get Casting Pattern Lookups List
 */
export const getCastingPatternLookupsListApiV1CastingPatternsLookupsGet = (
  params?: GetCastingPatternLookupsListApiV1CastingPatternsLookupsGetParams,
  signal?: AbortSignal,
) => {
  return customMutator<CastingPatternLookupsListResponse>({
    url: `/api/v1/casting-patterns/lookups`,
    method: 'GET',
    params,
    signal,
  })
}

export const getGetCastingPatternLookupsListApiV1CastingPatternsLookupsGetQueryKey = (
  params?: GetCastingPatternLookupsListApiV1CastingPatternsLookupsGetParams,
) => {
  return [`/api/v1/casting-patterns/lookups`, ...(params ? [params] : [])] as const
}

export const getGetCastingPatternLookupsListApiV1CastingPatternsLookupsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
  TError = HttpValidationError,
>(
  params?: GetCastingPatternLookupsListApiV1CastingPatternsLookupsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
        TError,
        TData
      >
    >
  },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetCastingPatternLookupsListApiV1CastingPatternsLookupsGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>
  > = ({ signal }) => getCastingPatternLookupsListApiV1CastingPatternsLookupsGet(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCastingPatternLookupsListApiV1CastingPatternsLookupsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>
>
export type GetCastingPatternLookupsListApiV1CastingPatternsLookupsGetQueryError =
  HttpValidationError

export function useGetCastingPatternLookupsListApiV1CastingPatternsLookupsGet<
  TData = Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
  TError = HttpValidationError,
>(
  params: undefined | GetCastingPatternLookupsListApiV1CastingPatternsLookupsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
          TError,
          Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCastingPatternLookupsListApiV1CastingPatternsLookupsGet<
  TData = Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
  TError = HttpValidationError,
>(
  params?: GetCastingPatternLookupsListApiV1CastingPatternsLookupsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
          TError,
          Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCastingPatternLookupsListApiV1CastingPatternsLookupsGet<
  TData = Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
  TError = HttpValidationError,
>(
  params?: GetCastingPatternLookupsListApiV1CastingPatternsLookupsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Casting Pattern Lookups List
 */

export function useGetCastingPatternLookupsListApiV1CastingPatternsLookupsGet<
  TData = Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
  TError = HttpValidationError,
>(
  params?: GetCastingPatternLookupsListApiV1CastingPatternsLookupsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCastingPatternLookupsListApiV1CastingPatternsLookupsGet>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCastingPatternLookupsListApiV1CastingPatternsLookupsGetQueryOptions(
    params,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
