/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import { faker } from '@faker-js/faker'
import { delay, http, HttpResponse } from 'msw'
import { CastingProductType, type CastingPatternLookupsListResponse } from '../../model'

export const getGetCastingPatternLookupsListApiV1CastingPatternsLookupsGetResponseMock = (
  overrideResponse: Partial<CastingPatternLookupsListResponse> = {},
): CastingPatternLookupsListResponse => ({
  data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.uuid(),
    castingProduct: {
      id: faker.string.uuid(),
      type: faker.helpers.arrayElement(Object.values(CastingProductType)),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    serialNumber: faker.string.alpha({ length: { min: 10, max: 20 } }),
  })),
  page: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  totalPages: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  totalItems: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  ...overrideResponse,
})

export const getGetCastingPatternLookupsListApiV1CastingPatternsLookupsGetMockHandler = (
  overrideResponse?:
    | CastingPatternLookupsListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CastingPatternLookupsListResponse> | CastingPatternLookupsListResponse),
) => {
  return http.get('*/api/v1/casting-patterns/lookups', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetCastingPatternLookupsListApiV1CastingPatternsLookupsGetResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}
export const getCastingPatternsMock = () => [
  getGetCastingPatternLookupsListApiV1CastingPatternsLookupsGetMockHandler(),
]
