/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { AddressCreateNote } from './addressCreateNote'
import type { AddressCreatePostalCode } from './addressCreatePostalCode'
import type { AddressType } from './addressType'

/**
 * Schema for creating a new Address.
 */
export interface AddressCreate {
  street: string
  postalCode?: AddressCreatePostalCode
  type: AddressType
  isPrimary: boolean
  note?: AddressCreateNote
  cityId: number
}
