/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { AddressDetailResponseNote } from './addressDetailResponseNote'
import type { AddressDetailResponsePostalCode } from './addressDetailResponsePostalCode'
import type { AddressType } from './addressType'

/**
 * Complete response schema for Address entity.
 */
export interface AddressDetailResponse {
  street: string
  postalCode?: AddressDetailResponsePostalCode
  type: AddressType
  isPrimary: boolean
  note?: AddressDetailResponseNote
  id: string
  cityId: number
  createdAt: string
  updatedAt: string
}
