/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { CountryShortResponse } from './countryShortResponse'

export interface CityDetailResponse {
  name: string
  nameLocal: string
  id: number
  country: CountryShortResponse
  createdAt: string
  updatedAt: string
}
