/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */

export type ContactOperationAction =
  (typeof ContactOperationAction)[keyof typeof ContactOperationAction]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContactOperationAction = {
  create: 'create',
  update: 'update',
  delete: 'delete',
} as const
