/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { ContactCreateNote } from './contactCreateNote'
import type { ContactType } from './contactType'

/**
 * Schema for creating a new Contact.
 */
export interface ContactCreate {
  type: ContactType
  value: string
  isPrimary: boolean
  note?: ContactCreateNote
}
