/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { CountryResponseCode3 } from './countryResponseCode3'
import type { CountryResponseNumericCode } from './countryResponseNumericCode'

export interface CountryResponse {
  code: string
  code3?: CountryResponseCode3
  numericCode?: CountryResponseNumericCode
  name: string
  nameLocal: string
  id: number
}
