/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { DepartmentShortResponse } from './departmentShortResponse'

export interface DepartmentListResponse {
  page: number
  totalPages: number
  totalItems: number
  data: DepartmentShortResponse[]
}
