/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */

export type GetPeopleListApiV1LookupsPeopleGetParams = {
  limit?: number | null
  search?: string | null
}
