/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { AddressResponse } from './addressResponse'
import type { ContactResponse } from './contactResponse'
import type { CountryShortResponse } from './countryShortResponse'
import type { OrganizationResponseRegistrationNumber } from './organizationResponseRegistrationNumber'
import type { OrganizationResponseTaxId } from './organizationResponseTaxId'

export interface OrganizationResponse {
  legalName: string
  registrationNumber?: OrganizationResponseRegistrationNumber
  taxId?: OrganizationResponseTaxId
  id: string
  country: CountryShortResponse
  contacts: ContactResponse[]
  addresses: AddressResponse[]
}
