/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationShortResponseRegistrationNumber } from './organizationShortResponseRegistrationNumber'
import type { OrganizationShortResponseTaxId } from './organizationShortResponseTaxId'

export interface OrganizationShortResponse {
  legalName: string
  registrationNumber?: OrganizationShortResponseRegistrationNumber
  taxId?: OrganizationShortResponseTaxId
  id: string
  countryName: string
}
