/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { DepartmentShortResponse } from './departmentShortResponse'
import type { PermissionResponseDescription } from './permissionResponseDescription'

export interface PermissionResponse {
  name: string
  description?: PermissionResponseDescription
  id: number
  department: DepartmentShortResponse
}
