/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { DepartmentShortResponse } from './departmentShortResponse'
import type { PermissionDetailResponseDescription } from './permissionDetailResponseDescription'

export interface PermissionDetailResponse {
  name: string
  description?: PermissionDetailResponseDescription
  id: number
  department: DepartmentShortResponse
  createdAt: string
  updatedAt: string
}
