/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { PersonListItemResponse } from './personListItemResponse'

/**
 * Paginated response container for Person list operations.

Extends base list response with Person-specific list items, providing pagination metadata and
standardized list structure.
 */
export interface PersonListResponse {
  page: number
  totalPages: number
  totalItems: number
  data: PersonListItemResponse[]
}
