/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { PositionShortResponse } from './positionShortResponse'

/**
 * Paginated response container for Position list operations.
 */
export interface PositionListResponse {
  page: number
  totalPages: number
  totalItems: number
  data: PositionShortResponse[]
}
