/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { TokenPairResponseRefreshToken } from './tokenPairResponseRefreshToken'

export interface TokenPairResponse {
  accessToken: string
  refreshToken?: TokenPairResponseRefreshToken
  tokenType?: string
}
