/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { UserShortResponseLastLoginAt } from './userShortResponseLastLoginAt'

export interface UserShortResponse {
  email: string
  id: string
  fullName: string
  isActive: boolean
  isSuperuser: boolean
  lastLoginAt?: UserShortResponseLastLoginAt
  roleNames: string[]
  permissionNames: string[]
}
