/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { PermissionResponse } from './permissionResponse'
import type { RoleResponse } from './roleResponse'
import type { UserDetailResponseLastLoginAt } from './userDetailResponseLastLoginAt'

export interface UserDetailResponse {
  email: string
  id: string
  isActive: boolean
  isSuperuser: boolean
  lastLoginAt?: UserDetailResponseLastLoginAt
  roles: RoleResponse[]
  permissions: PermissionResponse[]
  createdAt: string
  updatedAt: string
}
