/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Molding Shop Service
 * OpenAPI spec version: 0.1.0
 */
import { faker } from '@faker-js/faker'
import { delay, http, HttpResponse } from 'msw'
import type { MoldingAreaLookupsListResponse } from '../../model'

export const getGetMoldingAreaLookupsListApiV1MoldingAreasLookupsGetResponseMock = (
  overrideResponse: Partial<MoldingAreaLookupsListResponse> = {},
): MoldingAreaLookupsListResponse => ({
  data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    pressureUnits: faker.helpers.arrayElement([
      faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
      undefined,
    ]),
  })),
  page: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  totalPages: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  totalItems: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  ...overrideResponse,
})

export const getGetMoldingAreaLookupsListApiV1MoldingAreasLookupsGetMockHandler = (
  overrideResponse?:
    | MoldingAreaLookupsListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<MoldingAreaLookupsListResponse> | MoldingAreaLookupsListResponse),
) => {
  return http.get('*/api/v1/molding-areas/lookups', async (info) => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetMoldingAreaLookupsListApiV1MoldingAreasLookupsGetResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}
export const getMoldingAreasMock = () => [
  getGetMoldingAreaLookupsListApiV1MoldingAreasLookupsGetMockHandler(),
]
