/**
 * @file Automatically generated by 'scripts/generate-explicit-api.mjs'.
 */

export type { CoreMakingMachineFormFields } from './ui/CoreMakingMachineForm/schema'
export type {
  CoreMakingMachineFormOptions,
  CoreMakingMachineFormInitialData,
} from './ui/CoreMakingMachineForm/CoreMakingMachineForm'
export { coreMakingMachineFormSchema } from './ui/CoreMakingMachineForm/schema'
export { coreMakingMachineRoutes } from './routes'
export { default as CoreMakingMachineForm } from './ui/CoreMakingMachineForm/CoreMakingMachineForm'
