/**
 * @file Automatically generated by 'scripts/generate-explicit-api.mjs'.
 */

export type { CoreMakingMachineFormFields } from './ui/CoreMakingMachineForm/schema'
export { coreMakingMachineFormSchema } from './ui/CoreMakingMachineForm/schema'
