/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */

export type AddressOperationAction =
  (typeof AddressOperationAction)[keyof typeof AddressOperationAction]

 
export const AddressOperationAction = {
  create: 'create',
  update: 'update',
  delete: 'delete',
} as const
