/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { CityUpdateCountryId } from './cityUpdateCountryId'
import type { CityUpdateName } from './cityUpdateName'
import type { CityUpdateNameLocal } from './cityUpdateNameLocal'

export interface CityUpdate {
  countryId?: CityUpdateCountryId
  name?: CityUpdateName
  nameLocal?: CityUpdateNameLocal
}
