/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { ContactCreate } from './contactCreate'
import type { ContactUpdate } from './contactUpdate'

export type ContactOperationData = ContactCreate | ContactUpdate | null
