/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { ContactDetailResponseNote } from './contactDetailResponseNote'
import type { ContactType } from './contactType'

/**
 * Complete response schema for Contact entity.
 */
export interface ContactDetailResponse {
  type: ContactType
  value: string
  isPrimary: boolean
  note?: ContactDetailResponseNote
  id: string
  createdAt: string
  updatedAt: string
}
