/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */

export interface CountryShortResponse {
  id: number
  code: string
  name: string
  nameLocal: string
}
