/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { DepartmentUpdateDescription } from './departmentUpdateDescription'
import type { DepartmentUpdateName } from './departmentUpdateName'

export interface DepartmentUpdate {
  name?: DepartmentUpdateName
  description?: DepartmentUpdateDescription
}
