/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { EmployeeProfileUpdateEmployeeNumber } from './employeeProfileUpdateEmployeeNumber'
import type { EmployeeProfileUpdateEmploymentStatus } from './employeeProfileUpdateEmploymentStatus'
import type { EmployeeProfileUpdateHiredAt } from './employeeProfileUpdateHiredAt'

/**
 * Schema for updating an existing EmployeeProfile.
 */
export interface EmployeeProfileUpdate {
  employeeNumber?: EmployeeProfileUpdateEmployeeNumber
  hiredAt?: EmployeeProfileUpdateHiredAt
  employmentStatus?: EmployeeProfileUpdateEmploymentStatus
}
