/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */

/**
 * Employment status enumeration for EmployeeProfile model
 */
export type EmploymentStatus = (typeof EmploymentStatus)[keyof typeof EmploymentStatus]

 
export const EmploymentStatus = {
  intern: 'intern',
  'full-time': 'full-time',
  'part-time': 'part-time',
  contract: 'contract',
  'on-leave': 'on-leave',
  suspended: 'suspended',
  terminated: 'terminated',
  retired: 'retired',
} as const
