/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationCreateAddresses } from './organizationCreateAddresses'
import type { OrganizationCreateContacts } from './organizationCreateContacts'
import type { OrganizationCreateRegistrationNumber } from './organizationCreateRegistrationNumber'
import type { OrganizationCreateTaxId } from './organizationCreateTaxId'

export interface OrganizationCreate {
  legalName: string
  registrationNumber?: OrganizationCreateRegistrationNumber
  taxId?: OrganizationCreateTaxId
  countryId: number
  contacts?: OrganizationCreateContacts
  addresses?: OrganizationCreateAddresses
}
