/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationUpdateAddressOperations } from './organizationUpdateAddressOperations'
import type { OrganizationUpdateContactOperations } from './organizationUpdateContactOperations'
import type { OrganizationUpdateCountryId } from './organizationUpdateCountryId'
import type { OrganizationUpdateLegalName } from './organizationUpdateLegalName'
import type { OrganizationUpdateRegistrationNumber } from './organizationUpdateRegistrationNumber'
import type { OrganizationUpdateTaxId } from './organizationUpdateTaxId'

export interface OrganizationUpdate {
  countryId?: OrganizationUpdateCountryId
  legalName?: OrganizationUpdateLegalName
  registrationNumber?: OrganizationUpdateRegistrationNumber
  taxId?: OrganizationUpdateTaxId
  contactOperations?: OrganizationUpdateContactOperations
  addressOperations?: OrganizationUpdateAddressOperations
}
