/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { AddressDetailResponse } from './addressDetailResponse'
import type { ContactDetailResponse } from './contactDetailResponse'
import type { CountryShortResponse } from './countryShortResponse'
import type { OrganizationDetailResponseRegistrationNumber } from './organizationDetailResponseRegistrationNumber'
import type { OrganizationDetailResponseTaxId } from './organizationDetailResponseTaxId'

export interface OrganizationDetailResponse {
  legalName: string
  registrationNumber?: OrganizationDetailResponseRegistrationNumber
  taxId?: OrganizationDetailResponseTaxId
  id: string
  country: CountryShortResponse
  contacts: ContactDetailResponse[]
  addresses: AddressDetailResponse[]
  createdAt: string
  updatedAt: string
}
