/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { PersonUpdateAddressOperations } from './personUpdateAddressOperations'
import type { PersonUpdateBirthDate } from './personUpdateBirthDate'
import type { PersonUpdateContactOperations } from './personUpdateContactOperations'
import type { PersonUpdateEmployeeProfileAction } from './personUpdateEmployeeProfileAction'
import type { PersonUpdateEmployeeProfileData } from './personUpdateEmployeeProfileData'
import type { PersonUpdateFirstName } from './personUpdateFirstName'
import type { PersonUpdateGender } from './personUpdateGender'
import type { PersonUpdateLastName } from './personUpdateLastName'
import type { PersonUpdateMiddleName } from './personUpdateMiddleName'
import type { PersonUpdateOrganizationIds } from './personUpdateOrganizationIds'
import type { PersonUpdatePhotoUrl } from './personUpdatePhotoUrl'
import type { PersonUpdatePositionIds } from './personUpdatePositionIds'

/**
 * Schema for updating Person with complex relationship operations.

Supports partial updates of person data and sophisticated operations on related entities
including creation, updates, and deletions. All fields are optional to support partial updates.
 */
export interface PersonUpdate {
  firstName?: PersonUpdateFirstName
  middleName?: PersonUpdateMiddleName
  lastName?: PersonUpdateLastName
  gender?: PersonUpdateGender
  birthDate?: PersonUpdateBirthDate
  photoUrl?: PersonUpdatePhotoUrl
  employeeProfileAction?: PersonUpdateEmployeeProfileAction
  employeeProfileData?: PersonUpdateEmployeeProfileData
  contactOperations?: PersonUpdateContactOperations
  addressOperations?: PersonUpdateAddressOperations
  organizationIds?: PersonUpdateOrganizationIds
  positionIds?: PersonUpdatePositionIds
}
