/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { Gender } from './gender'
import type { PersonCreateAddresses } from './personCreateAddresses'
import type { PersonCreateBirthDate } from './personCreateBirthDate'
import type { PersonCreateContacts } from './personCreateContacts'
import type { PersonCreateEmployeeProfile } from './personCreateEmployeeProfile'
import type { PersonCreateMiddleName } from './personCreateMiddleName'
import type { PersonCreateOrganizationIds } from './personCreateOrganizationIds'
import type { PersonCreatePhotoUrl } from './personCreatePhotoUrl'
import type { PersonCreatePositionIds } from './personCreatePositionIds'

/**
 * Schema for creating a new Person with related entities.

Extends PersonBase to include core personal information.
 */
export interface PersonCreate {
  firstName: string
  middleName?: PersonCreateMiddleName
  lastName: string
  gender: Gender
  birthDate?: PersonCreateBirthDate
  photoUrl?: PersonCreatePhotoUrl
  employeeProfile?: PersonCreateEmployeeProfile
  contacts?: PersonCreateContacts
  addresses?: PersonCreateAddresses
  organizationIds?: PersonCreateOrganizationIds
  positionIds?: PersonCreatePositionIds
}
