/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { EmployeeProfileResponse } from './employeeProfileResponse'

export type PersonResponseEmployeeProfile = EmployeeProfileResponse | null
