/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Main Service
 * OpenAPI spec version: 0.1.0
 */
import type { RoleResponseDescription } from './roleResponseDescription'

export interface RoleResponse {
  name: string
  description?: RoleResponseDescription
  id: number
}
